### ISSUE TITLE
missing module br_netfilter

### ISSUE THREAD

**Issue by neimv** [radxa/rockchip-bsp#13]
Hello, I have a problem with module: br_netfilter, when I execute modprobe br_netfilter I get: modprobe: FATAL: Module br_netfilter not found in directory /lib/modules/4.19.193-31-rockchip-g044735a22a0e. I use rock3a and Ubuntu 20.04.4 LTS.

I like to use with docker swarm, any suggestion??

Thanks

**Comment by jack-ma** [comment]
we will fix this.

**Comment by StephenInVamrs** [comment]
@neimv 

Thanks for reporting this.

To solve your issue, please try the following steps.

1.Uncomment line like "deb http://apt.radxa.com/focal-testing/ focal main" in file /etc/apt/sources.list.d/apt-radxa-com.list to add testing source. 

```
deb http://apt.radxa.com/focal-stable/ focal main
deb http://apt.radxa.com/focal-testing/ focal main
```

2.Upgrade kernel to the latest, 4.19.193-42

```
$ sudo apt-get update
$ sudo apt-get install -y linux-4.19-rock-3-latest
```

3.Reboot and check the current kernel version with command `uname -r`. And install module `br_netfilter`.

**Comment by neimv** [comment]
Awesome, @StephenInVamrs I check and execute and looks fine, in this moment I can create my swarm with one services.

Thanks for the solution
