### ISSUE TITLE
How to build rootfs for Ubuntu?

### ISSUE THREAD

**Issue by darkgirl** [radxa/rockchip-bsp#14]
Hi,
I found that you have Ubutun server image on this page: https://wiki.radxa.com/Rockpi4/downloads
But I did not find the source of it, I only found branchs about debian in https://github.com/radxa/rk-rootfs-build .
so, Where can I find the ubuntu server rootfs?

Thank you.

**Comment by jack-ma** [comment]
Hi,

The new image release(Ubuntu Server and Debian desktop) are now built from: https://github.com/radxa/debos-radxa

**Comment by darkgirl** [comment]
> Hi,
> 
> The new image release(Ubuntu Server and Debian desktop) are now built from: https://github.com/radxa/debos-radxa

Thank you very much.
